name: HippoArch CI

on:
  push:
    branches-ignore: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ShellCheck
        run: sudo apt-get install -y shellcheck

      - name: Lint
        run: make lint

      - name: Security Scan
        run: make security

      - name: Syntax Check
        run: make test-syntax
